name: CI/CD Pipeline for Python Requests Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-python-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest tests
        run: |
          pytest tests/ -v --html=reports/report.html --self-contained-html
        env:
          BASE_URL: ${{ secrets.BASE_URL }}  # Se o BASE_URL estiver em segredos do GitHub

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report
          path: reports/report.html

      - name: Upload test logs (if needed)
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-logs
          path: logs/*.log  # Ajuste se os logs estiverem em outro diretório